### ISSUE TITLE
Palm regression: manually generated certificates fail to be accessible with error 500

### ISSUE THREAD

**Issue by throwaway-a** [openedx/wg-build-test-release#295]
While I was working to upgrade to Palm, I stopped to test that manually-created completion certificates was working (because it previously broke for me from Koa to Lilac.) I confirmed they were working fine in Olive.

Now that I've successfully upgraded to Palm, I've confirmed they've broken again. (I think a new test case needs to be created for these.)

Replication instructions:

1. Activate certificates on a class
2. Go to the Live View of the class -> Instructor -> Certificates
3. Add a student account to the exception list
4. Generate certificate (if necessary, it seemed to auto-generate for me)
5. Log in from a different browser / incognito tab as the student account
6. Go to the Progress page. 
7. Under "Your certificate is available!" on the right, click "View my certificate"

Result:

"There has been a 500 error on the MySiteName servers

Please wait a few seconds and then reload the page."

With the following error found in the tutor logs, pertaining to the certificate which was at URL mysite.com/certificates/0343d8892a1a4cb1b29f2f0abc32210c

```
tutor_local-lms-1            |   File "/openedx/edx-platform/common/djangoapps/edxmako/shortcuts.py", line 178, in render_to_string
tutor_local-cms-worker-1     | Traceback (most recent call last):
tutor_local-lms-1            |     return template.render(dictionary, request)
tutor_local-lms-1            |   File "/openedx/edx-platform/common/djangoapps/edxmako/template.py", line 82, in render
tutor_local-lms-1            |     return self.mako_template.render_unicode(**context_dictionary)
tutor_local-lms-1            |   File "/openedx/venv/lib/python3.8/site-packages/mako/template.py", line 444, in render_unicode
tutor_local-lms-1            |     return runtime._render(
tutor_local-lms-1            |   File "/openedx/venv/lib/python3.8/site-packages/mako/runtime.py", line 874, in _render
tutor_local-lms-1            |     _render_context(
tutor_local-lms-1            |   File "/openedx/venv/lib/python3.8/site-packages/mako/runtime.py", line 916, in _render_context
tutor_local-lms-1            |     _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
tutor_local-lms-1            |   File "/openedx/venv/lib/python3.8/site-packages/mako/runtime.py", line 943, in _exec_template
tutor_local-lms-1            |     callable_(context, *args, **kwargs)
tutor_local-lms-1            |   File "/tmp/mako_lms/1ff981c2157d500713c1ce6bf7fdbce2/certificates/accomplishment-base.html.py", line 80, in render_body
tutor_local-lms-1            |     __M_writer(js_escaped_string(ga_4_id ))
tutor_local-lms-1            | TypeError: 'Undefined' object is not callable
tutor_local-lms-1            | [pid: 7|app: 0|req: 108/346] 172.18.0.2 () {54 vars in 3031 bytes} [Mon Jun 12 17:44:42 2023] GET /certificates/0343d8892a1a4cb1b29f2f0abc32210c => generated 9313 bytes in 318 msecs (HTTP/1.1 500) 7 headers in 520 bytes (1 switches on core 0)
```

And
```
tutor_local-lms-1            | Traceback (most recent call last):
tutor_local-lms-1            |   File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
tutor_local-lms-1            |     response = get_response(request)
tutor_local-lms-1            |   File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
tutor_local-lms-1            |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
tutor_local-lms-1            |   File "/opt/pyenv/versions/3.8.15/lib/python3.8/contextlib.py", line 75, in inner
tutor_local-lms-1            |     return func(*args, **kwds)
tutor_local-lms-1            |   File "/openedx/edx-platform/./lms/djangoapps/certificates/views/webview.py", line 505, in render_cert_by_uuid
```

and

```
tutor_local-redis-1          | 1:M 12 Jun 2023 17:32:16.946 * Background saving terminated with success
tutor_local-lms-1            |     return func(request, *args, **kwargs)
tutor_local-redis-1          | 1:M 12 Jun 2023 17:37:17.032 * 10 changes in 300 seconds. Saving...
tutor_local-lms-1            |   File "/openedx/venv/lib/python3.8/site-packages/edx_django_utils/plugins/pluggable_override.py", line 77, in wrapper
tutor_local-lms-1            |     return prev_fn(*args, **kwargs)
tutor_local-lms-1            |   File "/openedx/edx-platform/./lms/djangoapps/certificates/views/webview.py", line 666, in render_html_view
tutor_local-lms-1            |     response = _render_valid_certificate(request, context, custom_template)
tutor_local-lms-1            |   File "/openedx/edx-platform/./lms/djangoapps/certificates/views/webview.py", line 756, in _render_valid_certificate
tutor_local-lms-1            |     return render_to_response("certificates/valid.html", context)
tutor_local-lms-1            |   File "/openedx/edx-platform/common/djangoapps/edxmako/shortcuts.py", line 188, in render_to_response
tutor_local-lms-1            |     return HttpResponse(render_to_string(template_name, dictionary, namespace, request), **kwargs)
tutor_local-lms-1            |   File "/openedx/edx-platform/common/djangoapps/edxmako/shortcuts.py", line 178, in render_to_string
tutor_local-lms-1            |     return template.render(dictionary, request)
tutor_local-lms-1            |   File "/openedx/edx-platform/common/djangoapps/edxmako/template.py", line 82, in render
tutor_local-lms-1            |     return self.mako_template.render_unicode(**context_dictionary)
tutor_local-lms-1            |   File "/openedx/venv/lib/python3.8/site-packages/mako/template.py", line 444, in render_unicode
tutor_local-lms-1            |     return runtime._render(
tutor_local-lms-1            |   File "/openedx/venv/lib/python3.8/site-packages/mako/runtime.py", line 874, in _render
tutor_local-lms-1            |     _render_context(
tutor_local-lms-1            |   File "/openedx/venv/lib/python3.8/site-packages/mako/runtime.py", line 916, in _render_context
tutor_local-lms-1            |     _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
tutor_local-lms-1            |   File "/openedx/venv/lib/python3.8/site-packages/mako/runtime.py", line 943, in _exec_template
tutor_local-cms-1            | 2023-06-12 17:43:15,886 ERROR 6 [root] [user None] [ip None] signals.py:22 - Uncaught exception from None
tutor_local-mfe-1            | {"level":"info","ts":1686591799.9196901,"logger":"http.log.access.log0","msg":"handled request","request":{"remote_ip":"172.18.0.2","remote_port":"36876","proto":"HTTP/1.1","method":"GET","host":"apps.test.mysite.com","uri":"/learning/runtime.b988c17eca0cfda7a09e.js"},"user_id":"","duration":0.000227141,"size":3377,"status":200}
tutor_local-cms-worker-1     |     es_response = self._es.search(index=self._prefixed_index_name, body=body, **kwargs)
tutor_local-cms-worker-1     |   File "/openedx/venv/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 168, in _wrapped
tutor_local-cms-worker-1     |     return func(*args, params=params, headers=headers, **kwargs)
tutor_local-cms-worker-1     |   File "/openedx/venv/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 1670, in search
tutor_local-cms-worker-1     |     return self.transport.perform_request(
tutor_local-cms-worker-1     |   File "/openedx/venv/lib/python3.8/site-packages/elasticsearch/transport.py", line 415, in perform_request
tutor_local-cms-worker-1     |     raise e
tutor_local-cms-worker-1     |   File "/openedx/venv/lib/python3.8/site-packages/elasticsearch/transport.py", line 381, in perform_request
tutor_local-cms-worker-1     |     status, headers_response, data = connection.perform_request(
tutor_local-cms-worker-1     |   File "/openedx/venv/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 277, in perform_request
tutor_local-cms-worker-1     |     self._raise_error(response.status, raw_data)
tutor_local-cms-worker-1     |   File "/openedx/venv/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 330, in _raise_error
tutor_local-cms-worker-1     |     raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
tutor_local-cms-worker-1     | elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'failed to create query: maxClauseCount is set to 1024')
tutor_local-cms-worker-1     | [2023-06-12 17:34:21,175: ERROR/ForkPoolWorker-3] Indexing error encountered, courseware index may be out of date course-v1:MyLongSiteNameIsLong+MyClass1+V1 - RequestError(400, 'search_phase_execution_exception', {'error': {'root_cause': [{'type': 'query_shard_exception', 'reason': 'failed to create query: maxClauseCount is set to 1024', 'index_uuid': 'tYsNt9SGQfyJwde3XICocQ', 'index': 'courseware_content'}], 'type': 'search_phase_execution_exception', 'reason': 'all shards failed', 'phase': 'query', 'grouped': True, 'failed_shards': [{'shard': 0, 'index': 'courseware_content', 'node': '4PM9xrdpQ9-qAI7vgRdLAA', 'reason': {'type': 'query_shard_exception', 'reason': 'failed to create query: maxClauseCount is set to 1024', 'index_uuid': 'tYsNt9SGQfyJwde3XICocQ', 'index': 'courseware_content', 'caused_by': {'type': 'too_many_clauses', 'reason': 'maxClauseCount is set to 1024'}}}]}, 'status': 400})
tutor_local-cms-worker-1     | Traceback (most recent call last):
tutor_local-cms-worker-1     |   File "/openedx/edx-platform/cms/djangoapps/contentstore/courseware_index.py", line 260, in index
tutor_local-cms-worker-1     |     cls.remove_deleted_items(searcher, structure_key, indexed_items)
tutor_local-cms-worker-1     |   File "/openedx/edx-platform/cms/djangoapps/contentstore/courseware_index.py", line 109, in remove_deleted_items
tutor_local-cms-worker-1     |     response = searcher.search(
tutor_local-cms-worker-1     |   File "/openedx/venv/lib/python3.8/site-packages/search/elastic.py", line 657, in search
tutor_local-cms-worker-1     |     es_response = self._es.search(index=self._prefixed_index_name, body=body, **kwargs)
tutor_local-cms-worker-1     |   File "/openedx/venv/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 168, in _wrapped
tutor_local-cms-worker-1     |     return func(*args, params=params, headers=headers, **kwargs)
tutor_local-cms-worker-1     |   File "/openedx/venv/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 1670, in search
tutor_local-cms-worker-1     |     return self.transport.perform_request(
tutor_local-cms-worker-1     |   File "/openedx/venv/lib/python3.8/site-packages/elasticsearch/transport.py", line 415, in perform_request
tutor_local-cms-worker-1     |     raise e
tutor_local-cms-worker-1     |   File "/openedx/venv/lib/python3.8/site-packages/elasticsearch/transport.py", line 381, in perform_request
tutor_local-cms-worker-1     |     status, headers_response, data = connection.perform_request(
tutor_local-cms-worker-1     |   File "/openedx/venv/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 277, in perform_request
tutor_local-cms-worker-1     |     self._raise_error(response.status, raw_data)
tutor_local-cms-worker-1     |   File "/openedx/venv/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 330, in _raise_error
tutor_local-cms-worker-1     |     raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
tutor_local-cms-worker-1     | elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'failed to create query: maxClauseCount is set to 1024')
```

and
```
tutor_local-cms-worker-1     | Traceback (most recent call last):
tutor_local-cms-worker-1     |   File "/openedx/venv/lib/python3.8/site-packages/search/elastic.py", line 657, in search
tutor_local-cms-worker-1     |     es_response = self._es.search(index=self._prefixed_index_name, body=body, **kwargs)
tutor_local-cms-worker-1     |   File "/openedx/venv/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 168, in _wrapped
tutor_local-cms-worker-1     |     return func(*args, params=params, headers=headers, **kwargs)
tutor_local-cms-worker-1     |   File "/openedx/venv/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 1670, in search
tutor_local-cms-worker-1     |     return self.transport.perform_request(
tutor_local-cms-worker-1     |   File "/openedx/venv/lib/python3.8/site-packages/elasticsearch/transport.py", line 415, in perform_request
tutor_local-cms-worker-1     |     raise e
tutor_local-cms-worker-1     |   File "/openedx/venv/lib/python3.8/site-packages/elasticsearch/transport.py", line 381, in perform_request
tutor_local-cms-worker-1     |     status, headers_response, data = connection.perform_request(
tutor_local-cms-1            | Traceback (most recent call last):
tutor_local-cms-1            |   File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
tutor_local-cms-1            |     response = get_response(request)
tutor_local-cms-1            |   File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
tutor_local-cms-1            |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
tutor_local-cms-1            |   File "/opt/pyenv/versions/3.8.15/lib/python3.8/contextlib.py", line 75, in inner
```

and
```
tutor_local-cms-1            |     return func(*args, **kwds)
tutor_local-cms-1            |   File "/openedx/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
tutor_local-cms-1            |     return view_func(*args, **kwargs)
tutor_local-cms-1            |   File "/openedx/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
tutor_local-cms-1            |     return self.dispatch(request, *args, **kwargs)
tutor_local-cms-1            |   File "/openedx/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
tutor_local-cms-1            |     response = self.handle_exception(exc)
tutor_local-cms-1            |   File "/openedx/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
tutor_local-cms-1            |     response = handler(request, *args, **kwargs)
tutor_local-cms-1            |   File "/openedx/edx-platform/./cms/djangoapps/contentstore/api/views/utils.py", line 136, in _wrapper_view
tutor_local-cms-1            |     return view(self, request, course_key, *args, **kwargs)
tutor_local-cms-1            |   File "/openedx/edx-platform/./cms/djangoapps/contentstore/api/views/course_validation.py", line 100, in get
tutor_local-cms-1            |     updates=self._updates_validation(course, request)
tutor_local-cms-1            |   File "/openedx/edx-platform/./cms/djangoapps/contentstore/api/views/course_validation.py", line 224, in _updates_validation
tutor_local-cms-1            |     updates = get_course_updates(updates_usage_key, provided_id=None, user_id=request.user.id)
tutor_local-cms-1            |   File "/openedx/edx-platform/./cms/djangoapps/contentstore/course_info_model.py", line 41, in get_course_updates
tutor_local-cms-1            |     course_update_items = get_course_update_items(course_updates, _get_index(provided_id))
tutor_local-cms-1            |   File "/openedx/edx-platform/./openedx/core/lib/xblock_utils/__init__.py", line 388, in get_course_update_items
tutor_local-cms-1            |     course_html_parsed = html.fromstring(course_updates.data)
tutor_local-cms-1            |   File "/openedx/venv/lib/python3.8/site-packages/lxml/html/__init__.py", line 873, in fromstring
tutor_local-cms-1            |     doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
tutor_local-cms-1            |   File "/openedx/venv/lib/python3.8/site-packages/lxml/html/__init__.py", line 759, in document_fromstring
```

**Comment by mariajgrimaldi** [comment]
This is working for me on the demo instance, for example, I manually generated [this certificate](https://palm.demo.overhang.io/certificates/b619c59e9b34400bad379cd7a9c1f662) on 13/06/2023. One of your services may not be correctly set up(?) Can you test on the demo instance? 
Also, please feel free to add test suggestions on the [suggestions tab in the testing sheet](https://docs.google.com/spreadsheets/d/1CX-smqwZ06eq6vyYCbNoIRZsuyGYNZoHiu_8zgmNj90/edit#gid=536490455).

**Comment by mariajgrimaldi** [comment]
I'll close this since I couldn't replicate this on the testing instance. I'll re-open it If it happens again.
